### ISSUE TITLE
When dragging an event, the event should stay coordinated with the mouse position

### ISSUE THREAD

**Issue by wflemingnz-retired** [ngx-d3timeline/ngx-d3timeline#128]
- Event Rectangle jumps immediately after dragging is stated
- Jump is noticeably larger when browser window has been scrolled

as seen in PD

**Comment by umarmohammed** [comment]
One way of overcoming this is to use the sourceEvent movementX/movementY. 

Note that touchevents don't have a movementX/movementY so this would prevent the drag from working on devices.

Using the devicePixelRatio caters for when the browser is zoomed in (or the resolution of the screen changed when plugged into HDMI).
```
    this.dragSubject.next({
      id: eventRectangle.id,
      dx:
        event.sourceEvent.movementX /
        event.sourceEvent.view.window.devicePixelRatio,
      dy:
        event.sourceEvent.movementY /
        event.sourceEvent.view.window.devicePixelRatio
    });
```

**Comment by wflemingnz-retired** [comment]
can't reproduce, assumed fixed by previous changes
