### ISSUE TITLE
Rename AxisViewModel and related models

### ISSUE THREAD

**Issue by wflemingnz-retired** [ngx-d3timeline/ngx-d3timeline#74]
Better name for TickInfo is TickMark.

Need to rename interface and relevant methods.

Ticks are the position of the TickMarks.
TickMark is the line and the label.

https://observablehq.com/@d3/scale-ticks
scale.**ticks** will return an array of values from the domain that can be used to position **tick marks**.

https://support.minitab.com/en-us/minitab/18/help-and-how-to/graphs/supporting-topics/graph-framework-elements/modifying-graph-axes-and-tick-marks/

**Comment by umarmohammed** [comment]
What do you think of AxisTick ?

**Comment by wflemingnz-retired** [comment]
Still refers to tick which I believe is the position rather than the visual representation. From what I've seen TickMark is the nomenclature.
